# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
   'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/kjobwidgets': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'plasma/kwayland': 'kf5'
    'plasma/breeze': '@same'
    'third-party/wayland': '@latest'

 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kcolorscheme': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/kjobwidgets': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kservice': 'Frameworks/6.24'
    'frameworks/kstatusnotifieritem': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'plasma/breeze': '@same'
    'third-party/wayland': '@latest'
Options:
 force-inject-asan: True
 require-passing-tests-on: ['@all']
